# for production
FrontBundle:
    resource: FrontBundle/Config/routes.yml
BackBundle:
    resource: BackBundle/Config/routes.yml
BackBundle:
    resource: BackBundle/Config/routes.yml
BackBundle:
    resource: BackBundle/Config/routes.yml